name: "Sign Assets"
description: "Create signatures of release assets and attach them to the release"
inputs:
  token:
    description: "Token to authenticate against the GitHub API (ususally 'secrets.GITHUB_TOKEN')"
    required: true
  gpg_key:
    description: "The key to import and sign assets with"
    required: true
  gpg_passphrase:
    description: "Optional passphrase to use the GPG key"
    required: false
  globs:
    description: "Glob patterns to filter the assets to be signed"
    required: false
runs:
  using: composite
  steps:
    - name: Install sign-assets binary
      shell: bash
      run: ${{ github.action_path }}/scripts/install.sh sign-assets
    - name: Sign assets
      shell: bash
      run: |
        key=$(mktemp)
        echo "${{ inputs.gpg_key }}" > $key

        sign-assets \
          --token ${{ inputs.token }} \
          --gpg-key $key \
          --gpg-passphrase ${{ inputs.gpg_passphrase }} \
          ${{ inputs.globs }}
