name: "Build Assets"
description: "Compile Rust binaries and attach them to the release"
inputs:
  token:
    description: "Token to authenticate against the GitHub API (ususally 'secrets.GITHUB_TOKEN')"
    required: true
  bin:
    description: "The binary to compile"
    required: true
  target:
    description: "Compilation target triple"
    required: false
  toolchain:
    description: "Rust toolchain to use"
    required: false
  features:
    description: "Additional crate features to activate during build"
    required: false
runs:
  using: composite
  steps:
    - name: Install build-assets binary
      shell: bash
      run: ${{ github.action_path }}/../scripts/install.sh build-assets
    - name: Build assets
      shell: bash
      run: build-assets
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        INPUT_TARGET: ${{ inputs.target }}
        INPUT_TOOLCHAIN: ${{ inputs.toolchain }}
        INPUT_BIN: ${{ inputs.bin }}
