[licenses]
allow = [
	"Apache-2.0",
	"Apache-2.0 WITH LLVM-exception",
	"BSD-3-Clause",
	"ISC",
	"MIT",
    "MPL-2.0",
    "OpenSSL",
]
exceptions = [
    { allow = ["Unicode-DFS-2016"], name = "unicode-ident" },
]

[licenses.private]
ignore = true

[[licenses.clarify]]
name = "ring"
version = "*"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 },
]

[bans]
skip = [
    { name = "bitflags", version = "1" },
]
