[package]
name = "hash-assets"
version = "1.0.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2021"
license = "AGPL-3.0-only"

[dependencies]
actions-common = { path = "../actions-common" }
anyhow = "1.0.53"
blake2 = "0.10.2"
clap = { version = "3.0.10", features = ["derive", "env"] }
globset = "0.4.8"
hex = "0.4.3"
rayon = "1.5.1"
sha2 = "0.10.1"
tracing = "0.1.29"

[dev-dependencies]
assert_fs = "1.0.7"
