[package]
name = "actions-common"
version = "0.1.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2021"
license = "MIT"

[dependencies]
anyhow = "1.0.57"
attohttpc = { version = "0.19.1", default-features = false, features = ["json", "compress", "tls-rustls"] }
envy = "0.4.2"
globset = "0.4.8"
serde = { version = "1.0.137", features = ["derive"] }
tracing = "0.1.34"
tracing-subscriber = "0.3.11"
