name: "Hash Assets"
description: "Create checksums of release assets and attach them to the release"
inputs:
  token:
    description: "Token to authenticate against the GitHub API (ususally 'secrets.GITHUB_TOKEN')"
    required: true
  globs:
    description: "Glob patterns to filter the assets to be hashed"
    required: false
runs:
  using: composite
  steps:
    - name: Install hash-assets binary
      shell: bash
      run: |
        set -euo pipefail

        cd /tmp

        curl -LsSfO https://github.com/dnaka91/actions/releases/latest/download/hash-assets-x86_64-unknown-linux-musl.tar.gz
        curl -LsSfO https://github.com/dnaka91/actions/releases/latest/download/checksums.b2
        curl -LsSfO https://github.com/dnaka91/actions/releases/latest/download/checksums.b2.asc

        gpg --recv-keys 24B536EEDC7D1FBCFC678E786C63F836857F5C34
        gpg --verify /tmp/checksums.b2.asc

        b2sum -c --ignore-missing /tmp/checksums.b2

        mkdir -p $HOME/.local/hash-assets/bin
        tar -xzf /tmp/hash-assets-x86_64-unknown-linux-musl.tar.gz -C $HOME/.local/hash-assets/bin
        rm -rf /tmp/*.{tar.gz,b2,b2.asc}

        echo "$HOME/.local/hash-assets/bin" >> $GITHUB_PATH
    - name: Hash assets
      shell: bash
      run: |
        hash-assets \
          --token ${{ inputs.token }} \
          ${{ inputs.globs }}
