name: "Hash Assets"
description: "Create checksums of release assets and attach them to the release"
inputs:
  token:
    description: "Token to authenticate against the GitHub API (ususally 'secrets.GITHUB_TOKEN')"
    required: true
  globs:
    description: "Glob patterns to filter the assets to be hashed"
    required: false
runs:
  using: composite
  steps:
    - name: Install hash-assets binary
      shell: bash
      run: ${{ github.action_path }}/../scripts/install.sh hash-assets
    - name: Hash assets
      shell: bash
      run: |
        hash-assets \
          --token ${{ inputs.token }} \
          ${{ inputs.globs }}
