[package]
name = "build-assets"
version = "1.0.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2021"
license = "AGPL-3.0-only"

[dependencies]
actions-common = { path = "../actions-common" }
anyhow = "1.0.53"
camino = "1.0.7"
cargo_metadata = "0.14.1"
flate2 = "1.0.22"
heck = "0.4.0"
serde = { version = "1.0.136", features = ["derive"] }
serde_with = { version = "1.11.0", default-features = false }
tar = "0.4.38"
target-lexicon = { version = "0.12.2", features = ["std"] }
time = "0.3.6"
tracing = "0.1.29"
zip = { version = "0.5.13", default-features = false, features = ["deflate"] }

[dev-dependencies]
assert_fs = "1.0.7"
time = { version = "0.3.6", features = ["macros"] }
