[package]
name = "build-assets"
version = "1.0.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2021"
license = "AGPL-3.0-only"

[dependencies]
actions-common = { path = "../actions-common" }
anyhow = "1.0.57"
camino = "1.0.9"
cargo_metadata = "0.14.2"
flate2 = "1.0.24"
heck = "0.4.0"
serde = { version = "1.0.137", features = ["derive"] }
serde_with = { version = "1.14.0", default-features = false }
tar = "0.4.38"
target-lexicon = { version = "0.12.4", features = ["std"] }
time = "0.3.9"
tracing = "0.1.34"
zip = { version = "0.6.2", default-features = false, features = ["deflate"] }

[dev-dependencies]
assert_fs = "1.0.7"
time = { version = "0.3.9", features = ["macros"] }
