[package]
name = "sign-assets"
version = "1.0.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2021"
license = "AGPL-3.0-only"

[dependencies]
actions-common = { path = "../actions-common" }
anyhow = "1.0.57"
globset = "0.4.8"
once_cell = "1.12.0"
rayon = "1.5.3"
serde = { version = "1.0.137", features = ["derive"] }
serde_with = { version = "1.14.0", default-features = false }
tempfile = "3.3.0"
tracing = "0.1.34"
which = "4.2.5"

[dev-dependencies]
assert_fs = "1.0.7"
