[package]
name = "sign-assets"
version = "1.0.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2021"
license = "AGPL-3.0-only"

[dependencies]
actions-common = { path = "../actions-common" }
anyhow = "1.0.53"
clap = { version = "3.0.10", features = ["derive", "env"] }
globset = "0.4.8"
once_cell = "1.9.0"
rayon = "1.5.1"
tracing = "0.1.29"
which = "4.2.2"

[dev-dependencies]
assert_fs = "1.0.7"
