name: release
permissions:
  contents: write
on:
  push:
    tags:
      - v[0-9]+.*
env:
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -C debuginfo=0 -D warnings
jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: taiki-e/create-gh-release-action@v1
        with:
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  upload-assets:
    name: Upload assets
    needs: create-release
    strategy:
      matrix:
        bin: [hash-assets, sign-assets]
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Rust
        uses: taiki-e/github-actions/install-rust@main
        with:
          toolchain: stable
      - name: Build and upload asset
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: ${{ matrix.bin }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  create-checksums:
    name: Create checksums
    needs: upload-assets
    runs-on: ubuntu-latest
    steps:
      - name: Download assets
        run: gh release download --repo "${{ github.repository }}" "${{ github.ref_name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create checksums
        run: b2sum -b *.tar.gz > checksums.b2
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name: Sign checksum files
        run: gpg -ba --yes checksums.b2
      - name: Upload checksums and signatures
        run: gh release upload --clobber --repo "${{ github.repository }}" "${{ github.ref_name }}" checksums.b2 checksums.b2.asc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
