name: release
permissions:
  contents: write
on:
  push:
    tags:
      - v[0-9]+.*
env:
  TAG: ${{ github.ref_name }}
  REPO: ${{ github.repository }}
jobs:
  create-release:
    name: Create draft release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create draft release
        run: gh release create "$TAG" --verify-tag --draft --generate-notes --title "Release $TAG"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  upload-assets:
    name: Upload assets
    needs: create-release
    strategy:
      matrix:
        bin: [build-assets, hash-assets, sign-assets]
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Build and upload asset
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: ${{ matrix.bin }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  upload-checksums:
    name: Create checksums
    needs: upload-assets
    runs-on: ubuntu-latest
    steps:
      - name: Download assets
        run: gh release download --repo "$REPO" "$TAG"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create checksums
        run: b2sum -b *.{tar.gz,zip} > checksums.b2
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name: Sign checksum files
        run: gpg -ba --yes checksums.b2
      - name: Upload checksums and signatures
        run: gh release upload --repo "$REPO" "$TAG" --clobber checksums.b2 checksums.b2.asc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  publish-release:
    name: Publish release
    runs-on: ubuntu-latest
    needs:
      - create-release
      - upload-assets
      - upload-checksums
    steps:
      - name: Publish release
        run: gh release edit --repo "$REPO" "$TAG" --draft=false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
